name: YAML validation

permissions:
  contents: read

on:
  push:
    paths:
      - 'elements/**/*.yaml'
      - 'events/**/*.yaml'
      - 'functions/**/*.yaml'
      - 'schemas/**/*.yaml'
      - 'tools/validate.sh'
  pull_request:
    paths:
      - 'elements/**/*.yaml'
      - 'events/**/*.yaml'
      - 'functions/**/*.yaml'
      - 'schemas/**/*.yaml'
      - 'tools/validate.sh'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true
      
      - name: Run validator
        run: tools/validate.sh
